# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Skill.find_or_create_by name: 'Active Directory', context: 'Product'
Skill.find_or_create_by name: 'ADABAS', context: 'Database'
Skill.find_or_create_by name: 'ADASTRIP', context: 'Tool'
Skill.find_or_create_by name: 'AFP', context: 'Tool'
Skill.find_or_create_by name: 'AI (Fuzzy Logic)', context: 'Technique'
Skill.find_or_create_by name: 'AIX/Unix', context: 'Operating System'
Skill.find_or_create_by name: 'Akka', context: 'Framework'
Skill.find_or_create_by name: 'ANT ', context: 'Tool'
Skill.find_or_create_by name: 'Apache Web Server', context: 'Product'
Skill.find_or_create_by name: 'ASP', context: 'Framework'
Skill.find_or_create_by name: 'ASP .NET', context: 'Framework'
Skill.find_or_create_by name: 'Assembler', context: 'Language'
Skill.find_or_create_by name: 'Avaya Dialogue Designer', context: 'Product'
Skill.find_or_create_by name: 'Brixton SNA Administration', context: 'Technique'
Skill.find_or_create_by name: 'C', context: 'Language'
Skill.find_or_create_by name: 'C# .Net', context: 'Language'
Skill.find_or_create_by name: 'C++', context: 'Language'
Skill.find_or_create_by name: 'CA Gen', context: 'Language'
Skill.find_or_create_by name: 'CA Software Change Manager', context: 'Product'
Skill.find_or_create_by name: 'Chameleon', context: 'Product'
Skill.find_or_create_by name: 'Champ', context: 'Product'
Skill.find_or_create_by name: 'CICS', context: 'Framework'
Skill.find_or_create_by name: 'Clear Case', context: 'Product'
Skill.find_or_create_by name: 'Clear Quest', context: 'Product'
Skill.find_or_create_by name: 'CLIST', context: 'Tool'
Skill.find_or_create_by name: 'Cobol', context: 'Language'
Skill.find_or_create_by name: 'Com Proxy / API Calls', context: 'Technique'
Skill.find_or_create_by name: 'CSS', context: 'Markup'
Skill.find_or_create_by name: 'Data Modelling', context: 'Technique'
Skill.find_or_create_by name: 'Data Power', context: 'Product'
Skill.find_or_create_by name: 'Database Design', context: 'Technique'
Skill.find_or_create_by name: 'Distributed processing concepts', context: 'Technique'
Skill.find_or_create_by name: 'DNS', context: 'Protocol'
Skill.find_or_create_by name: 'Docker', context: 'Product'
Skill.find_or_create_by name: 'DP4', context: 'Tool'
Skill.find_or_create_by name: 'DPSYSNC', context: 'Tool'
Skill.find_or_create_by name: 'DropWizard', context: 'Framework'
Skill.find_or_create_by name: 'Drupal 7 ', context: 'Product'
Skill.find_or_create_by name: 'EMC Input Accel 5.2 & 6.1 Scanning', context: 'Product'
Skill.find_or_create_by name: 'Entity Framework', context: 'Framework'
Skill.find_or_create_by name: 'ERD Diagramming', context: 'Technique'
Skill.find_or_create_by name: 'Fileaid', context: 'Tool'
Skill.find_or_create_by name: 'FTP / SFTP / SFT Plus', context: 'Protocol'
Skill.find_or_create_by name: 'Git', context: 'Tool'
Skill.find_or_create_by name: 'Google mini', context: 'Product'
Skill.find_or_create_by name: 'GuardiEN', context: 'Product'
Skill.find_or_create_by name: 'HA Clustering (Power HA)', context: 'Technique'
Skill.find_or_create_by name: 'HTML', context: 'Markup'
Skill.find_or_create_by name: 'HTTP', context: 'Protocol'
Skill.find_or_create_by name: 'IIS Administration', context: 'Technique'
Skill.find_or_create_by name: 'IIS configuration and hardening', context: 'Technique'
Skill.find_or_create_by name: 'IMS', context: 'Tool'
Skill.find_or_create_by name: 'Puppet', context: 'Product'
Skill.find_or_create_by name: 'Ansible', context: 'Product'
Skill.find_or_create_by name: 'Chef', context: 'Product'
Skill.find_or_create_by name: 'Sale', context: 'Product'
Skill.find_or_create_by name: 'ISPF', context: 'Tool'
Skill.find_or_create_by name: 'ITIM QAB', context: 'Tool'
Skill.find_or_create_by name: 'Java Enterprise Edition', context: 'Language'
Skill.find_or_create_by name: 'Java Standard Edition', context: 'Language'
Skill.find_or_create_by name: 'Javascript', context: 'Language'
Skill.find_or_create_by name: 'JCL', context: 'Language'
Skill.find_or_create_by name: 'Jenkins', context: 'Tool'
Skill.find_or_create_by name: 'Jira', context: 'Product'
Skill.find_or_create_by name: 'JMS', context: 'Framework'
Skill.find_or_create_by name: 'JQuery', context: 'Framework'
Skill.find_or_create_by name: 'JSON', context: 'Markup'
Skill.find_or_create_by name: 'JUnit', context: 'Tool'
Skill.find_or_create_by name: 'Mac OS X', context: 'Operating System'
Skill.find_or_create_by name: 'Maven', context: 'Tool'
Skill.find_or_create_by name: 'Message Broker', context: 'Product'
Skill.find_or_create_by name: 'Mockito', context: 'Tool'
Skill.find_or_create_by name: 'MongoDB', context: 'Database'
Skill.find_or_create_by name: 'MQ', context: 'Product'
Skill.find_or_create_by name: 'MS Windows Server W2K / Server2008', context: 'Operating System'
Skill.find_or_create_by name: 'MS Office Macros', context: 'Product'
Skill.find_or_create_by name: 'MySQL', context: 'Database'
Skill.find_or_create_by name: 'N20', context: 'Product'
Skill.find_or_create_by name: 'N203GL', context: 'Product'
Skill.find_or_create_by name: 'Natural', context: 'Language'
Skill.find_or_create_by name: 'Natural Security', context: 'Technique'
Skill.find_or_create_by name: 'Nginx', context: 'Product'
Skill.find_or_create_by name: 'NodeJS', context: 'Framework'
Skill.find_or_create_by name: 'OPCA', context: 'Tool'
Skill.find_or_create_by name: 'Payment processing', context: 'Technique'
Skill.find_or_create_by name: 'Perl', context: 'Language'
Skill.find_or_create_by name: 'PHP', context: 'Language'
Skill.find_or_create_by name: 'Play', context: 'Framework'
Skill.find_or_create_by name: 'Postgresql', context: 'Database'
Skill.find_or_create_by name: 'PREDICT', context: 'Tool'
Skill.find_or_create_by name: 'Pro C', context: 'Language'
Skill.find_or_create_by name: 'Python', context: 'Language'
Skill.find_or_create_by name: 'QAS', context: 'Product'
Skill.find_or_create_by name: 'RabbitMQ', context: 'Product'
Skill.find_or_create_by name: 'Rails (RoR)', context: 'Framework'
Skill.find_or_create_by name: 'Rally', context: 'Product'
Skill.find_or_create_by name: 'RequireJs', context: 'Framework'
Skill.find_or_create_by name: 'REXX', context: 'Language'
Skill.find_or_create_by name: 'RRDF', context: 'Language'
Skill.find_or_create_by name: 'Ruby', context: 'Language'
Skill.find_or_create_by name: 'SAG Adabas Vista', context: 'Product'
Skill.find_or_create_by name: 'SBT', context: 'Tool'
Skill.find_or_create_by name: 'Scala', context: 'Language'
Skill.find_or_create_by name: 'ScalaTest', context: 'Tool'
Skill.find_or_create_by name: 'Selenium WebDriver', context: 'Product'
Skill.find_or_create_by name: 'Sharepoint 2013 Administration', context: 'Technique'
Skill.find_or_create_by name: 'Sharepoint 2013 Dashboard Designer', context: 'Technique'
Skill.find_or_create_by name: 'Sharepoint 2013 Development', context: 'Technique'
Skill.find_or_create_by name: 'SNA Concepts', context: 'Technique'
Skill.find_or_create_by name: 'Source Safe', context: 'Product'
Skill.find_or_create_by name: 'Spray', context: 'Tool'
Skill.find_or_create_by name: 'Spring Framework', context: 'Framework'
Skill.find_or_create_by name: 'SQL', context: 'Language'
Skill.find_or_create_by name: 'SSL', context: 'Protocol'
Skill.find_or_create_by name: 'StaffWare / Broker Support Tibco 8.1', context: 'Protocol'
Skill.find_or_create_by name: 'Swift', context: 'Language'
Skill.find_or_create_by name: 'Team Foundation Server 2008', context: 'Product'
Skill.find_or_create_by name: 'Team Foundation Server 2013', context: 'Product'
Skill.find_or_create_by name: 'Test Director', context: 'Product'
Skill.find_or_create_by name: 'TSO', context: 'Tool'
Skill.find_or_create_by name: 'Tuxedo Comms', context: 'Product'
Skill.find_or_create_by name: 'Unix Shell Scripting', context: 'Language'
Skill.find_or_create_by name: 'VB Script', context: 'Language'
Skill.find_or_create_by name: 'VB .NET', context: 'Framework'
Skill.find_or_create_by name: 'VB6 ', context: 'Language'
Skill.find_or_create_by name: 'VBA', context: 'Language'
Skill.find_or_create_by name: 'VBS', context: 'Language'
Skill.find_or_create_by name: 'Vignette vrs 20.1 Plus', context: 'Product'
Skill.find_or_create_by name: 'Visual SourceSafe', context: 'Product'
Skill.find_or_create_by name: 'VXML', context: 'Markup'
Skill.find_or_create_by name: 'W3C Accessibility', context: 'Technique'
Skill.find_or_create_by name: 'Web Forms', context: 'Technique'
Skill.find_or_create_by name: 'WLA / Cron', context: 'Tool'
Skill.find_or_create_by name: 'XML', context: 'Markup'
Skill.find_or_create_by name: 'XSL', context: 'Markup'
Skill.find_or_create_by name: 'ZeroMQ', context: 'Product'
Skill.find_or_create_by name: 'W3C Accessibility', context: 'Technique'
Skill.find_or_create_by name: 'Google Analytics', context: 'Product'
Skill.find_or_create_by name: 'Google Web Toolkit', context: 'Framework'
Skill.find_or_create_by name: 'OBPM 10', context: 'Product'
Skill.find_or_create_by name: 'UML', context: 'Technique'
Skill.find_or_create_by name: 'LDAP', context: 'Protocol'
