# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Skill.destroy_all

Skill.create name: 'Scala', context: 'Language'
Skill.create name: 'Node.js', context: 'Framework'
Skill.create name: 'Dropwizard', context: 'Framework'
Skill.create name: 'Vert.x', context: 'Framework'
Skill.create context: 'Product', name: 'Active Directory'
Skill.create context: 'Database', name: 'ADABAS'
Skill.create context: 'Tool', name: 'ADASTRIP'
Skill.create context: 'Tool', name: 'AFP'
Skill.create context: 'Technique', name: 'AI (Fuzzy Logic)'
Skill.create context: 'Operating System', name: 'AIX/Unix'
Skill.create context: 'Framework', name: 'Akka'
Skill.create context: 'Tool', name: 'ANT '
Skill.create context: 'Product', name: 'Apache Web Server'
Skill.create context: 'Framework', name: 'ASP'
Skill.create context: 'Framework', name: 'ASP .NET'
Skill.create context: 'Language', name: 'Assembler'
Skill.create context: 'Product', name: 'Avaya Dialogue Designer'
Skill.create context: 'Technique', name: 'Brixton SNA Administration'
Skill.create context: 'Language', name: 'C'
Skill.create context: 'Language', name: 'C# .Net'
Skill.create context: 'Language', name: 'C++'
Skill.create context: 'Language', name: 'CA Gen'
Skill.create context: 'Product', name: 'CA Software Change Manager'
Skill.create context: 'Product', name: 'Chameleon'
Skill.create context: 'Product', name: 'Champ'
Skill.create context: 'Framework', name: 'CICS'
Skill.create context: 'Product', name: 'Clear Case'
Skill.create context: 'Product', name: 'Clear Quest'
Skill.create context: 'Tool', name: 'CLIST'
Skill.create context: 'Language', name: 'Cobol'
Skill.create context: 'Technique', name: 'Com Proxy / API Calls'
Skill.create context: 'Markup', name: 'CSS'
Skill.create context: 'Technique', name: 'Data Modelling'
Skill.create context: 'Product', name: 'Data Power'
Skill.create context: 'Technique', name: 'Database Design'
Skill.create context: 'Technique', name: 'Distributed processing concepts'
Skill.create context: 'Protocol', name: 'DNS'
Skill.create context: 'Product', name: 'Docker'
Skill.create context: 'Tool', name: 'DP4'
Skill.create context: 'Tool', name: 'DPSYSNC'
Skill.create context: 'Framework', name: 'DropWizard'
Skill.create context: 'Product', name: 'Drupal 7 '
Skill.create context: 'Product', name: 'EMC Input Accel 5.2 & 6.1 Scanning'
Skill.create context: 'Framework', name: 'Entity Framework'
Skill.create context: 'Technique', name: 'ERD Diagramming'
Skill.create context: 'Framework', name: 'Fabric3'
Skill.create context: 'Tool', name: 'Fileaid'
Skill.create context: 'Protocol', name: 'FTP, SFTP, SSH, SFT Plus'
Skill.create context: 'Tool', name: 'Git'
Skill.create context: 'Product', name: 'Google mini'
Skill.create context: 'Product', name: 'GuardiEN'
Skill.create context: 'Technique', name: 'HA Clustering (Power HA)'
Skill.create context: 'Markup', name: 'HTML'
Skill.create context: 'Protocol', name: 'HTTP'
Skill.create context: 'Technique', name: 'IIS Administration'
Skill.create context: 'Technique', name: 'IIS v4 5 and 7.5 (configuration and hardening)'
Skill.create context: 'Tool', name: 'IMS'
Skill.create context: 'Technique', name: 'Infrasture Orchestration (Puppet / Ansible / Chef / Salt)'
Skill.create context: 'Tool', name: 'ISPF'
Skill.create context: 'Tool', name: 'ITIM QAB'
Skill.create context: 'Language', name: 'Java Enterprise Edition (JEE)'
Skill.create context: 'Language', name: 'Java Standard Edition (JSE)'
Skill.create context: 'Language', name: 'Javascript'
Skill.create context: 'Language', name: 'JCL'
Skill.create context: 'Tool', name: 'Jenkins'
Skill.create context: 'Product', name: 'Jira'
Skill.create context: 'Framework', name: 'JMS'
Skill.create context: 'Framework', name: 'JQuery'
Skill.create context: 'Markup', name: 'JSON'
Skill.create context: 'Tool', name: 'JUnit'
Skill.create context: 'Technique', name: 'Linux Admin'
Skill.create context: 'Operating System', name: 'Mac OS X'
Skill.create context: 'Tool', name: 'Maven'
Skill.create context: 'Product', name: 'Message Broker'
Skill.create context: 'Tool', name: 'Mockito'
Skill.create context: 'Database', name: 'MongoDB'
Skill.create context: 'Product', name: 'MQ'
Skill.create context: 'Operating System', name: 'MS Windows Server W2K / Server2008'
Skill.create context: 'Product', name: 'MS Word/Excel & Macros'
Skill.create context: 'Database', name: 'MySQL'
Skill.create context: 'Product', name: 'N20'
Skill.create context: 'Product', name: 'N203GL'
Skill.create context: 'Language', name: 'Natural'
Skill.create context: 'Technique', name: 'Natural Security'
Skill.create context: 'Product', name: 'Nginx'
Skill.create context: 'Framework', name: 'NodeJS'
Skill.create context: 'Tool', name: 'OPCA'
Skill.create context: 'Database', name: 'Oracle 10 and 11g'
Skill.create context: 'Database', name: 'Oracle 10.x Application Server'
Skill.create context: 'Database', name: 'Oracle 10.x Database Administration'
Skill.create context: 'Database', name: 'Oracle 10.x Database Backup & Recovery (RMAN)'
Skill.create context: 'Database', name: 'Oracle 10.x Database Performance Tuning'
Skill.create context: 'Database', name: 'Oracle 11.2 Database Administration'
Skill.create context: 'Database', name: 'Oracle 11.2 Database Backup & Recovery (RMAN)'
Skill.create context: 'Database', name: 'Oracle 11.2 Database Performance Tuning'
Skill.create context: 'Database', name: 'Oracle 9.2 Database Administration'
Skill.create context: 'Database', name: 'Oracle 9.2 Database Backup & Recovery (RMAN)'
Skill.create context: 'Database', name: 'Oracle 9.2 Database Performance Tuning'
Skill.create context: 'Database', name: 'Oracle Access Manager 11g'
Skill.create context: 'Database', name: 'Oracle Directory Services 11g'
Skill.create context: 'Database', name: 'Oracle Discoverer'
Skill.create context: 'Database', name: 'Oracle Identity Manager 11g'
Skill.create context: 'Language', name: 'Oracle PL/SQL'
Skill.create context: 'Database', name: 'Oracle SQL'
Skill.create context: 'Database', name: 'Oracle SQL Gateway'
Skill.create context: 'Database', name: 'Oracle Stored Procedures'
Skill.create context: 'Database', name: 'Oracle Streams'
Skill.create context: 'Database', name: 'Oracle Weblogic Server 10g & 11g'
Skill.create context: 'Technique', name: 'Payment processing'
Skill.create context: 'Language', name: 'Perl'
Skill.create context: 'Language', name: 'PHP'
Skill.create context: 'Framework', name: 'Play'
Skill.create context: 'Database', name: 'Postgresql'
Skill.create context: 'Tool', name: 'PREDICT'
Skill.create context: 'Language', name: 'Pro C'
Skill.create context: 'Language', name: 'Python'
Skill.create context: 'Product', name: 'QAS'
Skill.create context: 'Product', name: 'RabbitMQ'
Skill.create context: 'Framework', name: 'Rails (RoR)'
Skill.create context: 'Product', name: 'Rally'
Skill.create context: 'Framework', name: 'RequireJs'
Skill.create context: 'Language', name: 'REXX'
Skill.create context: 'Language', name: 'RRDF'
Skill.create context: 'Language', name: 'Ruby'
Skill.create context: 'Product', name: 'SAG Adabas Vista'
Skill.create context: 'Tool', name: 'SBT'
Skill.create context: 'Language', name: 'Scala'
Skill.create context: 'Tool', name: 'ScalaTest'
Skill.create context: 'Product', name: 'Selenium WebDriver'
Skill.create context: 'Technique', name: 'Sharepoint 2013 Administration'
Skill.create context: 'Technique', name: 'Sharepoint 2013 Dashboard Designer'
Skill.create context: 'Technique', name: 'Sharepoint 2013 Development'
Skill.create context: 'Technique', name: 'SNA Concepts'
Skill.create context: 'Product', name: 'Source Safe'
Skill.create context: 'Tool', name: 'Spray'
Skill.create context: 'Framework', name: 'Spring Framework'
Skill.create context: 'Language', name: 'SQL'
Skill.create context: 'Database', name: 'SQL Server'
Skill.create context: 'Database', name: 'SQL Server 2000 Database Administration'
Skill.create context: 'Database', name: 'SQL Server 2000 Performance Tuning'
Skill.create context: 'Database', name: 'SQL Server 2005 Analysis Services'
Skill.create context: 'Database', name: 'SQL Server 2005 Database Administration'
Skill.create context: 'Database', name: 'SQL Server 2005 Integration Services'
Skill.create context: 'Database', name: 'SQL Server 2005 Performance Tuning'
Skill.create context: 'Database', name: 'SQL Server 2005 Reporting Services'
Skill.create context: 'Database', name: 'SQL Server 2008 Analysis Services'
Skill.create context: 'Database', name: 'SQL Server 2008 Database Administration'
Skill.create context: 'Database', name: 'SQL Server 2008 Integration Services'
Skill.create context: 'Database', name: 'SQL Server 2008 Mirroring'
Skill.create context: 'Database', name: 'SQL Server 2008 Performance Tuning'
Skill.create context: 'Database', name: 'SQL Server 2008 Reporting Services'
Skill.create context: 'Database', name: 'SQL Server 2014 Analysis Services'
Skill.create context: 'Database', name: 'SQL Server 2014 Database Administration'
Skill.create context: 'Database', name: 'SQL Server 2014 Integration Services'
Skill.create context: 'Database', name: 'SQL Server 2014 Mirroring'
Skill.create context: 'Database', name: 'SQL Server 2014 Performance Tuning'
Skill.create context: 'Database', name: 'SQL Server 2014 Reporting Services'
Skill.create context: 'Database', name: 'SQL Server Performance Replication'
Skill.create context: 'Protocol', name: 'SSL'
Skill.create context: 'Protocol', name: 'StaffWare / Broker Support Tibco 8.1'
Skill.create context: 'Language', name: 'Swift'
Skill.create context: 'Product', name: 'Team Foundation Server 2008'
Skill.create context: 'Product', name: 'Team Foundation Server 2013'
Skill.create context: 'Product', name: 'Test Director'
Skill.create context: 'Tool', name: 'TSO'
Skill.create context: 'Product', name: 'Tuxedo Comms'
Skill.create context: 'Language', name: 'Unix Shell Scripting'
Skill.create context: 'Language', name: 'VB Script'
Skill.create context: 'Framework', name: 'VB .NET'
Skill.create context: 'Language', name: 'VB6 '
Skill.create context: 'Language', name: 'VBA'
Skill.create context: 'Language', name: 'VBS'
Skill.create context: 'Product', name: 'Vignette vrs 20.1 Plus'
Skill.create context: 'Product', name: 'Visual SourceSafe'
Skill.create context: 'Markup', name: 'VXML'
Skill.create context: 'Technique', name: 'W3C Accessibility'
Skill.create context: 'Technique', name: 'Web Forms'
Skill.create context: 'Operating System', name: 'WINDOWS 2008 Administration skills'
Skill.create context: 'Operating System', name: 'Windows Server 2008 Admin/Suport'
Skill.create context: 'Tool', name: 'WLA / Cron'
Skill.create context: 'Markup', name: 'XML'
Skill.create context: 'Markup', name: 'XSL'
Skill.create context: 'Product', name: 'ZeroMQ'
Skill.create context: 'Technique', name: 'W3C Accessibility'

Team.destroy_all

Team.create name: 'Test team 1'
Team.create name: 'Test team 2'
